// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EntityTransformPacket extends Table {
  public static EntityTransformPacket getRootAsEntityTransformPacket(ByteBuffer _bb) { return getRootAsEntityTransformPacket(_bb, new EntityTransformPacket()); }
  public static EntityTransformPacket getRootAsEntityTransformPacket(ByteBuffer _bb, EntityTransformPacket obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public EntityTransformPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String entityId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer entityIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer entityIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public Matrix4f transform() { return transform(new Matrix4f()); }
  public Matrix4f transform(Matrix4f obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startEntityTransformPacket(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addEntityId(FlatBufferBuilder builder, int entityIdOffset) { builder.addOffset(0, entityIdOffset, 0); }
  public static void addTransform(FlatBufferBuilder builder, int transformOffset) { builder.addStruct(1, transformOffset, 0); }
  public static int endEntityTransformPacket(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

