// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema.packet;

public final class EntityAttribute {
  private EntityAttribute() { }
  public static final byte NONE = 0;
  public static final byte PlayerEntityAttribute = 1;

  public static final String[] names = { "NONE", "PlayerEntityAttribute", };

  public static String name(int e) { return names[e]; }
}

