// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LoginSuccessfulPacket extends Table {
  public static LoginSuccessfulPacket getRootAsLoginSuccessfulPacket(ByteBuffer _bb) { return getRootAsLoginSuccessfulPacket(_bb, new LoginSuccessfulPacket()); }
  public static LoginSuccessfulPacket getRootAsLoginSuccessfulPacket(ByteBuffer _bb, LoginSuccessfulPacket obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public LoginSuccessfulPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PlayerInfo player() { return player(new PlayerInfo()); }
  public PlayerInfo player(PlayerInfo obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createLoginSuccessfulPacket(FlatBufferBuilder builder,
      int playerOffset) {
    builder.startObject(1);
    LoginSuccessfulPacket.addPlayer(builder, playerOffset);
    return LoginSuccessfulPacket.endLoginSuccessfulPacket(builder);
  }

  public static void startLoginSuccessfulPacket(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(0, playerOffset, 0); }
  public static int endLoginSuccessfulPacket(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

