// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema.packet;

public final class PacketType {
  private PacketType() { }
  public static final byte NONE = 0;
  public static final byte WorldStatePacket = 1;
  public static final byte LoginPacket = 2;
  public static final byte LoginSuccessfulPacket = 3;
  public static final byte ClientReadyPacket = 4;
  public static final byte EntityTransformPacket = 5;

  public static final String[] names = { "NONE", "WorldStatePacket", "LoginPacket", "LoginSuccessfulPacket", "ClientReadyPacket", "EntityTransformPacket", };

  public static String name(int e) { return names[e]; }
}

