// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerInfo extends Table {
  public static PlayerInfo getRootAsPlayerInfo(ByteBuffer _bb) { return getRootAsPlayerInfo(_bb, new PlayerInfo()); }
  public static PlayerInfo getRootAsPlayerInfo(ByteBuffer _bb, PlayerInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayerInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int userId() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String username() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer usernameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public Matrix4f transform() { return transform(new Matrix4f()); }
  public Matrix4f transform(Matrix4f obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startPlayerInfo(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUserId(FlatBufferBuilder builder, int userId) { builder.addInt(0, userId, 0); }
  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) { builder.addOffset(1, usernameOffset, 0); }
  public static void addTransform(FlatBufferBuilder builder, int transformOffset) { builder.addStruct(2, transformOffset, 0); }
  public static int endPlayerInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

