// automatically generated by the FlatBuffers compiler, do not modify

package com.adam.adventure.lib.flatbuffer.schema;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LoginPacket extends Table {
    public static LoginPacket getRootAsLoginPacket(final ByteBuffer _bb) {
        return getRootAsLoginPacket(_bb, new LoginPacket());
    }

    public static LoginPacket getRootAsLoginPacket(final ByteBuffer _bb, final LoginPacket obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(final int _i, final ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public LoginPacket __assign(final int _i, final ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String username() {
        final int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer usernameAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer usernameInByteBuffer(final ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public static int createLoginPacket(final FlatBufferBuilder builder,
                                        final int usernameOffset) {
        builder.startObject(1);
        LoginPacket.addUsername(builder, usernameOffset);
        return LoginPacket.endLoginPacket(builder);
    }

    public static void startLoginPacket(final FlatBufferBuilder builder) {
        builder.startObject(1);
    }

    public static void addUsername(final FlatBufferBuilder builder, final int usernameOffset) {
        builder.addOffset(0, usernameOffset, 0);
    }

    public static int endLoginPacket(final FlatBufferBuilder builder) {
        final int o = builder.endObject();
        return o;
    }
}

